### ISSUE TITLE
spirit of the watcher

### ISSUE THREAD

**Issue by checco-01** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#97] opened 2019-11-16 15:31 UTC
## Description
after killing the watcher the quest will not update
## Base information 
* Minecraft version:1.12.2
* Minecraft Forge version:14.23.5.2847
* TolkienCraft II version:1.12.2-2.0.20

## Crash report
```
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment] 2019-11-21 22:48
The issue is with the entity name in the quest...forgot to update it so it will be fixed in the next pack update.  The fix is to change the name of the entity to remove all of the spaces in the name in the quest or temporarily change the name of the NPC that shows up to add spaces to its name. (you should have also gotten a token, though it is supposed to be claimed fairly quickly)

**Closed as completed by GreatOrator** 2019-11-21 22:48 UTC
